import java.awt.Color;
import java.util.Random;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author PC Mateo
 */
public class Enfermedad extends javax.swing.JFrame {

    /**
     * Creates new form Enfermedad0
     */
    public Enfermedad() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    int xMouse,yMouse;
    private String disease;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultado = new javax.swing.JTextArea();
        decoración = new javax.swing.JPanel();
        bgTitulo = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        frasesTxt = new javax.swing.JTextArea();
        logoname = new javax.swing.JLabel();
        tituloTxt = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnExit = new javax.swing.JPanel();
        exitTxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setAutoscrolls(true);
        jScrollPane1.setColumnHeaderView(null);

        resultado.setEditable(false);
        resultado.setColumns(20);
        resultado.setFont(new java.awt.Font("Poppins Light", 0, 18)); // NOI18N
        resultado.setLineWrap(true);
        resultado.setRows(5);
        resultado.setBorder(null);
        resultado.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                resultadoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(resultado);

        bg.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 1040, 490));

        decoración.setBackground(new java.awt.Color(35, 122, 112));

        javax.swing.GroupLayout decoraciónLayout = new javax.swing.GroupLayout(decoración);
        decoración.setLayout(decoraciónLayout);
        decoraciónLayout.setHorizontalGroup(
            decoraciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1100, Short.MAX_VALUE)
        );
        decoraciónLayout.setVerticalGroup(
            decoraciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        bg.add(decoración, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 1100, 10));

        bgTitulo.setBackground(new java.awt.Color(17, 77, 77));
        bgTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane3.setBorder(null);

        frasesTxt.setEditable(false);
        frasesTxt.setBackground(new java.awt.Color(17, 77, 77));
        frasesTxt.setColumns(20);
        frasesTxt.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        frasesTxt.setForeground(new java.awt.Color(255, 255, 255));
        frasesTxt.setLineWrap(true);
        frasesTxt.setRows(5);
        frasesTxt.setBorder(null);
        frasesTxt.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                frasesTxtAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane3.setViewportView(frasesTxt);

        bgTitulo.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 40, 390, 70));

        logoname.setBackground(new java.awt.Color(255, 255, 255));
        logoname.setFont(new java.awt.Font("Poppins Black", 1, 18)); // NOI18N
        logoname.setForeground(new java.awt.Color(0, 250, 150));
        logoname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoname.setText("Alimentus");
        bgTitulo.add(logoname, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 170, -1));

        tituloTxt.setFont(new java.awt.Font("Poppins Black", 0, 30)); // NOI18N
        tituloTxt.setForeground(new java.awt.Color(255, 255, 255));
        tituloTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloTxt.setText("ENFERMEDADES");
        bgTitulo.add(tituloTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 500, 130));

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo4.png"))); // NOI18N
        bgTitulo.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 129));

        jPanel3.setBackground(new java.awt.Color(17, 77, 77));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(17, 77, 77));
        btnExit.setForeground(new java.awt.Color(255, 51, 51));
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        exitTxt.setFont(new java.awt.Font("Poppins Light", 0, 24)); // NOI18N
        exitTxt.setForeground(new java.awt.Color(255, 255, 255));
        exitTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTxt.setText("X");
        exitTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitTxt.setPreferredSize(new java.awt.Dimension(40, 40));
        exitTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnExitLayout = new javax.swing.GroupLayout(btnExit);
        btnExit.setLayout(btnExitLayout);
        btnExitLayout.setHorizontalGroup(
            btnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );
        btnExitLayout.setVerticalGroup(
            btnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1056, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bgTitulo.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 30));

        bg.add(bgTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 130));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resultadoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_resultadoAncestorAdded
        Arreglos enfer = new Arreglos();
        int numEnfermedad;

        this.disease=CaracteristicasFisicas.enfermedadCmb.getSelectedItem().toString();

        String message = "Estos son los alimentos que te pueden ayudar a combatir: " + this.disease + ": ";
        
        if(this.disease.equalsIgnoreCase("Azúcar alto")){
            numEnfermedad = 0;
            resultado.setText(message);
            resultado.append(enfer.arreglo_enfermedades(numEnfermedad));
        }else if(this.disease.equalsIgnoreCase("Colesterol alto")){
            numEnfermedad = 1;
            resultado.setText(message);
            resultado.append(enfer.arreglo_enfermedades(numEnfermedad));
        }else if(this.disease.equalsIgnoreCase("Anemia")){
            numEnfermedad = 2;
            resultado.setText(message);
            resultado.append(enfer.arreglo_enfermedades(numEnfermedad));
        }else if(this.disease.equalsIgnoreCase("Problemas digestivos")){
            numEnfermedad = 3;
            resultado.setText(message);
            resultado.append(enfer.arreglo_enfermedades(numEnfermedad));
        }
    }//GEN-LAST:event_resultadoAncestorAdded

    private void frasesTxtAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_frasesTxtAncestorAdded
        int numAleatorio = 0;
        numAleatorio = (int) (Math.random() * 12+1);

        //Frase motivacional
        Arreglos frase = new Arreglos();
        frasesTxt.setText(frase.frasesMotivacionales(numAleatorio));
    }//GEN-LAST:event_frasesTxtAncestorAdded

    private void exitTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitTxtMouseClicked

    private void exitTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseEntered
        btnExit.setBackground(Color.red);
        exitTxt.setForeground(Color.black);
    }//GEN-LAST:event_exitTxtMouseEntered

    private void exitTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseExited
        btnExit.setBackground(new Color(17, 77, 77));
        exitTxt.setForeground(Color.white);
    }//GEN-LAST:event_exitTxtMouseExited

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanel3MouseDragged

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel3MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Enfermedad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Enfermedad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Enfermedad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Enfermedad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Enfermedad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel bgTitulo;
    private javax.swing.JPanel btnExit;
    private javax.swing.JPanel decoración;
    private javax.swing.JLabel exitTxt;
    private javax.swing.JTextArea frasesTxt;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel logoname;
    private javax.swing.JTextArea resultado;
    private javax.swing.JLabel tituloTxt;
    // End of variables declaration//GEN-END:variables
}
